project:
  type: website
  output-dir: docs
  resources:
    - "https://www.untrm.edu.pe/assets/images/untrmazul.png"
    
website:
  page-navigation: true
  title: "EFECTO DEL TRATAMIENTO DE ESCARIFICACIÓN CON ARENA SOBRE LA GERMINACIÓN DE SEMILLAS DE SOYA (Glycine max L.)"
  description: "EFECTO DEL TRATAMIENTO DE ESCARIFICACIÓN CON ARENA SOBRE LA GERMINACIÓN DE SEMILLAS DE SOYA (Glycine max L.)"
  site-url: "https://datasciencebox.org/"
  
  repo-url: https://github.com/Victor-Hugo-Baldera/Analisis_datos_Unidad-II
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@vhugo"
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU3YM5lz5piQaGd1CGOFO1WQxl7XvURnrk1Q&s"

  page-footer:
    left: "Esta página fue creada con ❤️ y [Quarto](https://quarto.org/)."
    background: "#153768"
    right: []

  navbar:
    background: "#153768"
    logo: "https://www.untrm.edu.pe/assets/images/untrmazul.png"
    align: center
    title: false
    collapse-below: lg
 
    right:
      - icon: github
        href: https://github.com/Victor-Hugo-Baldera/Analisis_datos_Unidad-II
        aria-label: GitHub

    left:
      - href: equipo.qmd
        icon: house-door-fill
        text: " "
      - text: "Introducción"
        href: index.qmd
      - text: "Materiales y Métodos"
        href: hello.qmd
      - text: "Resultados y Discusiones"
        href: content.qmd
      - text: "Conclusiones"
        href: infrastructure.qmd
      - text: "Referencias"
        href: design.qmd

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

freeze: auto

editor: visual
