---
title: "Referencias"
editor: visual
---

1.  Gaur, R. S., & Pandey, A. P. (2020). Germplasm Evaluation of Soyabean (Glycine max L.) through Morphological and Quality Characterization. International Journal of Current Microbiology and Applied Sciences, 9(8), 9-15. https://doi.org/10.20546/ijcmas.2020.908.002

2.  Mishra, R., Tripathi, M. K., Sikarwar, R. S., Singh, Y., & Tripathi, N. (2024). Soybean (Glycine max L. Merrill): A Multipurpose Legume Shaping Our World. PLANT CELL BIOTECHNOLOGY AND MOLECULAR BIOLOGY, 25(3-4), 17-37. https://doi.org/10.56557/pcbmb/2024/v25i3-48643

3.  Rocha, C. B., Nehring, R., & Silva, S. D. E. (2022). Soy Without Borders: The Transnational Dynamics of Commodity Frontiers In South America (1971-2019). Global Environment, 15(3), 423-455. https://doi.org/10.3197/ge.2022.150301

4.  Sinegovsky, M. O. (2023). Soybean it is the crop of world farming. Вестник российской сельскохозяйственной науки, 5, 22-25. https://doi.org/10.31857/2500-2082/2023/5/22-25

5.  Soares, J. R. S., Ramos, R. S., Da Silva, R. S., Neves, D. V. C., & Picanço, M. C. (2021). Climate change impact assessment on worldwide rain fed soybean based on species distribution models. Tropical Ecology, 62(4), 612-625. https://doi.org/10.1007/s42965-021-00174-1

6.  Barrios, R., Universidad de Oriente, Postgrado de Agricultura Tropical, Campus Juanico, Maturín, Monagas, Venezuela., Romero Marcano, G., & Universidad de Oriente, Postgrado de Agricultura Tropical, Campus Juanico, Maturín, Monagas, Venezuela. (2024). Germinación de semillas de leguminosas inoculadas con diferentes dosis de bioinsumos. Revista Espanciencia, 15(1), 54-63. https://doi.org/10.51260/revista_espamciencia.v15i1.499 Carrillo, F., & Rucabado, A. L. (2021). Evaluación de la viabilidad de semillas de sacha inchi Plukenetia volubilis L. Conservadas a 4°C. Anales Científicos, 82(2), Article 2. https://doi.org/10.21704/ac.v82i2.1793

7.  Elizalde, S. I. B. (2022). Mejoramiento de la expresión de los atributos de calidad fisiológica y economía tecnológica del uso de bioestimuladores aplicados a semillas de forrajeras.

8.  Flores M, E., Caceres, W. E., Aguirre T, L., & Castillo, M. S. (2020). Efecto de la escarificación en la germinación de semillas de soya forrajera perenne (Neonotonia wightii). Revista de Investigaciones Veterinarias del Perú, 31(3). https://doi.org/10.15381/rivep.v31i3.16728

9.  Sun, Y., & Gong, Y. (2024). Research advances on the hard seededness trait of soybean and the underlying regulatory mechanisms. Frontiers in Plant Science, 15. https://doi.org/10.3389/fpls.2024.1419962
